ci: added block to merge directly with dev

diff --git a/.github/workflows/block_merge_with_main.yml b/.github/workflows/block_merge_with_main.yml
--- a/.github/workflows/block_merge_with_main.yml
+++ b/.github/workflows/block_merge_with_main.yml
@@ -4,11 +4,17 @@ on:
   pull_request:
 
 jobs:
-  check_branch:
+  block_damaging_merges:
     runs-on: ubuntu-latest
     steps:
       - name: Check branch
         if: github.base_ref == 'main' && github.head_ref != 'dev' && startsWith(github.head_ref, 'hotfix/') == false
         run: |
           echo "ERROR: You can only merge to main from dev or a hotfix branch."
+          exit 1
+
+      - name: Check if merging to dev
+        if: github.base_ref == 'dev' && github.head_ref != 'test'
+        run: |
+          echo "ERROR: You can only merge to dev from test."
           exit 1
